# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*.rb
    - Guardfile

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 140

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Metrics/ParameterLists:
  Max: 12
